#!/bin/sh -e

systemctl enable elasticsearch
systemctl start elasticsearch

STATUS='localhost:9200/_cluster/health?pretty'

while true; do
	echo waiting for Elasticsearch to start...
	sleep 10
	if curl $STATUS -s | python -m json.tool | egrep -q '"status": "green"'; then
		break
	fi
done

pelias-schema-create-index
